version: "3.9"

services:
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - "4002:4002"
    volumes:
      - ./api:/api
      - /api/node_modules
  # TODO: add serve script after development finished
  # client:
  #   build: ./client
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./client:/client
  #     - /client/node_modules
